### GET request to example server
GET http://localhost:8080/api/questions/1

###

### Send POST request with json body
POST http://localhost:8080/api/questions
Content-Type: application/json

{
  "title": "what is spring boot?"
}

### Send PUT request with json body
PUT http://localhost:8080/api/questions/1
Content-Type: application/json

{
  "title": "what is java?"
}

### DELETE a question
DELETE http://localhost:8080/api/questions/1
